project_name: hoop
builds:
  - id: hoop
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
    - amd64
    - arm64
    main: ./client/main.go
    binary: hoop
    ldflags:
    - -s -w
    - -X github.com/runopsio/hoop/common/version.version={{ .Tag }}
    - -X github.com/runopsio/hoop/common/version.gitCommit={{ .Commit }}
    - -X github.com/runopsio/hoop/common/version.buildDate={{ .Date }}
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
blobs:
- provider: s3
  region: us-east-1
  bucket: hoopartifacts
  ids:
  - hoop
dockers:
  - dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    image_templates:
    - "hoophq/hoop:{{ .Tag }}-arm64v8"
    - "hoophq/hoop:latest-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=hoop"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"
    extra_files:
    - rootfs
  - dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
    - "hoophq/hoop:{{ .Tag }}-amd64"
    - "hoophq/hoop:latest-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=hoop"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Tag}}"
    extra_files:
    - rootfs
docker_manifests:
  # https://goreleaser.com/customization/docker_manifest/
  - name_template: hoophq/hoop:{{ .Tag }}
    image_templates:
      - hoophq/hoop:{{ .Tag }}-amd64
      - hoophq/hoop:{{ .Tag }}-arm64v8
  - name_template: hoophq/hoop:latest
    image_templates:
      - hoophq/hoop:latest-amd64
      - hoophq/hoop:latest-arm64v8
# brews:
#   - tap:
#       owner: runopsio
#       name: hoop
#     url_template: "https://github.com/runopsio/hoop/releases/download/{{ .Version }}/{{ .ArtifactName }}"
#     commit_author:
#       name: runopsteam
#       email: team@runops.io
#     commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
#     homepage: "https://github.com/runopsio/hoop"
#     description: "Runops Proxy forwards remote tcp connections locally."
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-{{ .Prerelease }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
