name: Agent Tools

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The semantic version to use to generate a new release'
        required: true
        type: string
      environment:
        description: 'Environment to generate the release'
        type: environment
        required: true

jobs:
  docker-publish-tools:
    runs-on: ubuntu-latest
    name: Docker Publish Agent Tools
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_LOGIN }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile.tools
          context: .
          platforms: linux/amd64
          push: true
          tags: hoophq/agent-tools:${{ github.event.inputs.version }}
